# Generated by Django 5.2.5 on 2025-10-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_embedding'),
        ('organisations', '0006_merge_20251005_0744'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['title'], name='opportuniti_title_80a0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organisation'], name='opportuniti_organis_d1d7aa_idx'),
        ),
    ]
