# Generated by Django 5.2.5 on 2025-10-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_opportuniti_title_80a0e0_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX opportunity_embedding_idx ON opportunities_opportunity USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);",
            reverse_sql="DROP INDEX IF EXISTS opportunity_embedding_idx;"
        ),
    ]
