# Generated by Django 5.2.5 on 2025-10-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_auto_20251010_0316'),
        ('organisations', '0006_merge_20251005_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, help_text='Job location (city, state, remote, etc.)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['location'], name='opportuniti_locatio_df5b7c_idx'),
        ),
    ]
