# Generated by Django 5.2.5 on 2025-08-31 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text content of the message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like voice content, tool calls, etc.')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Yes Human will create a subject for the thread based on the context of the conversation.', max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, help_text='ID of the user who owns this thread', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the thread was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the thread was last updated.')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threads.message')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('threads.message',),
        ),
        migrations.CreateModel(
            name='HumanMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threads.message')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('threads.message',),
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threads.message')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('threads.message',),
        ),
        migrations.CreateModel(
            name='ToolMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threads.message')),
                ('tool_name', models.CharField(blank=True, help_text='Name of the tool that was executed', max_length=100)),
                ('tool_result', models.JSONField(blank=True, default=dict, help_text='Result of the tool execution')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('threads.message',),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread'),
        ),
    ]
