# Generated by Django 5.2.5 on 2025-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether this thread belongs to an anonymous user'),
        ),
        migrations.AddField(
            model_name='thread',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True),
        ),
    ]
