# Generated by Django 5.2.5 on 2025-09-12 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator_perspective', models.CharField(choices=[('employer', 'Employer searching for candidates'), ('candidate', 'Candidate searching for opportunities')], max_length=20)),
                ('total_evaluated', models.IntegerField(help_text='Total profiles/opportunities evaluated')),
                ('llm_judged_count', models.IntegerField(default=0, help_text='How many got LLM evaluation')),
                ('llm_threshold_percent', models.FloatField(default=0.2, help_text='Top % that get LLM judged (0.2 = 20%)')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sets', to='opportunities.opportunity')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sets', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_score', models.FloatField(help_text='Final evaluation score (0.0-1.0)')),
                ('rank_in_set', models.IntegerField(help_text='Ranking within this evaluation set')),
                ('component_scores', models.JSONField(default=dict, help_text="Pipeline breakdown: {'structured': 0.8, 'semantic': 0.6, 'llm_judge': 0.9}")),
                ('was_llm_judged', models.BooleanField(default=False)),
                ('llm_reasoning', models.TextField(blank=True, help_text='LLM explanation (if judged)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='opportunities.opportunity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='profiles.profile')),
                ('evaluation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.evaluationset')),
            ],
        ),
        migrations.AddIndex(
            model_name='evaluationset',
            index=models.Index(fields=['evaluator_perspective', 'created_at'], name='evaluations_evaluat_354b18_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationset',
            index=models.Index(fields=['is_complete'], name='evaluations_is_comp_0a394f_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluation_set', 'rank_in_set'], name='evaluations_evaluat_2b60bf_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['final_score'], name='evaluations_final_s_19c461_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['was_llm_judged'], name='evaluations_was_llm_94c91a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('evaluation_set', 'profile', 'opportunity')},
        ),
    ]
