# Generated by Django 5.2.5 on 2025-10-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
