# Generated by Django 5.2.5 on 2025-10-05 02:43

from django.db import migrations
from django.utils.text import slugify


def populate_slugs_forwards(apps, schema_editor):
    """Populate slugs for existing organisations."""
    Organisation = apps.get_model('organisations', 'Organisation')

    for org in Organisation.objects.all():
        if not org.slug:
            base_slug = slugify(org.name)
            slug = base_slug
            counter = 1

            # Handle duplicates
            while Organisation.objects.filter(slug=slug).exclude(pk=org.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            org.slug = slug
            org.save(update_fields=['slug'])


def populate_slugs_reverse(apps, schema_editor):
    """Reverse migration - clear slugs."""
    Organisation = apps.get_model('organisations', 'Organisation')

    Organisation.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_description_organisation_industry_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_slugs_forwards,
            reverse_code=populate_slugs_reverse
        ),
    ]
