# Generated by Django 5.2.5 on 2025-10-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
