# Generated by Django 5.2.5 on 2025-10-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_populate_slugs'),
        ('organisations', '0005_add_slug_unique_constraint'),
    ]

    operations = [
    ]
