[build]
builder = "Nixpacks"

[deploy]
healthcheckPath = "/health.json"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[deploy.env]
NODE_ENV = "production"
# Point frontend to your API deployment
VITE_API_URL = "https://yh-api-talentco-production.up.railway.app"
# Additional allowed hosts (comma-separated)
VITE_ALLOWED_HOSTS = "yh-labs-ui-talentco-production.up.railway.app"
