[build]
builder = "Nixpacks"

[deploy]
healthcheckPath = "/health.json"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[deploy.env]
NODE_ENV = "production"
