# Generated by Django 5.2.5 on 2025-10-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_make_session_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='run_id',
            field=models.UUIDField(blank=True, default=None, help_text='LangSmith run ID for this specific message (child run)', null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='langsmith_trace_id',
            field=models.UUIDField(blank=True, default=None, help_text='LangSmith trace ID for the conversation root run', null=True),
        ),
    ]
