# Generated by Django 5.2.5 on 2025-08-21 10:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique agent name', max_length=100, unique=True)),
                ('endpoint_url', models.URLField(blank=True, help_text="Agent's callback URL", max_length=500, null=True)),
                ('capabilities', models.JSONField(default=list, help_text='List of agent capabilities')),
                ('metadata', models.JSONField(default=dict, help_text='Additional agent metadata')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'a2a_agents',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, help_text='Conversation topic', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Conversation metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to='a2a.agent')),
            ],
            options={
                'db_table': 'a2a_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='A2AMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('task', 'Task Assignment'), ('response', 'Task Response'), ('request', 'Information Request'), ('broadcast', 'Broadcast Message'), ('notification', 'Notification'), ('error', 'Error Message')], default='request', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Message subject/title', max_length=255)),
                ('payload', models.JSONField(help_text='Message content and data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Background')], default=3)),
                ('response_required', models.BooleanField(default=False)),
                ('response_timeout', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_message', to='a2a.a2amessage')),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='a2a.agent')),
                ('to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='a2a.agent')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a2a.conversation')),
            ],
            options={
                'db_table': 'a2a_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(default='general', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Task parameters and configuration')),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('result', models.JSONField(blank=True, help_text='Task result data', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='a2a.agent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='a2a.agent')),
                ('request_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='a2a.a2amessage')),
            ],
            options={
                'db_table': 'a2a_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['from_agent', 'created_at'], name='a2a_message_from_ag_17cb75_idx'),
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['to_agent', 'status'], name='a2a_message_to_agen_262023_idx'),
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['status', 'priority'], name='a2a_message_status_d1c38a_idx'),
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['conversation', 'created_at'], name='a2a_message_convers_3a7370_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='a2a_tasks_assigne_8631e3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'created_at'], name='a2a_tasks_created_146e97_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='a2a_tasks_status_0ca7ab_idx'),
        ),
    ]
