# Generated by Django 5.2.5 on 2025-08-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2amessage',
            name='callback_url',
            field=models.URLField(blank=True, help_text='Optional callback URL for delivery/read notifications', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='a2amessage',
            name='delivery_attempts',
            field=models.IntegerField(default=0, help_text='Number of callback delivery attempts'),
        ),
        migrations.AddField(
            model_name='a2amessage',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last delivery error, if any'),
        ),
    ]
