# Generated by Django 5.2.5 on 2025-10-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_normalize_groups'),
        ('organisations', '0002_organisation_description_organisation_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_organisations',
            field=models.ManyToManyField(blank=True, help_text='Organisations this user can manage', related_name='managers', to='organisations.organisation'),
        ),
    ]
