[build]
builder = "Nixpacks"

[build.env]
PYTHON_VERSION = "3.13"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 600
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
startCommand = "daphne -b 0.0.0.0 -p $PORT yeshuman.asgi:application"

[deploy.env]
DJANGO_SETTINGS_MODULE = "yeshuman.settings"
PYTHONPATH = "/app"
